### PR TITLE
Refactor build scripts

### PR DESCRIPTION
**Pull request by mcbouslog**
- refactor build scripts, primarily so staging uses `webpack.production.config.js`
- updates GitHub workflows for new build scripts

### CODE REVIEW

**Comment by mcbouslog** [comment]
Used https://github.com/zooniverse/pfe-lab/blob/master/package.json as a reference, but open to suggestions.

**Comment by eatyourgreens** [comment]
`NODE_ENV` conflicts with the Webpack build mode in the staging script. That’s confusing. 
https://webpack.js.org/configuration/mode/

**Review by eatyourgreens — APPROVED** [review]
Let’s see how this works. We can always iterate on the settings.

**Comment by mcbouslog** [comment]
Agreed that doesn't look right with the staging env and production mode. But sounds good on revisiting too, I'll merge this to see if works. Thanks @eatyourgreens !

**Pull request merged**
