### PR TITLE
Change name to Zooniverse Classroom + Node 14

### PR DESCRIPTION
**Pull request by shaunanoordin**
## PR Overview

This repo was recently renamed from `edu-api-front-end` (Education API Front End) to `classroom` (to properly reflect its actual branding of Zooniverse Classrooms). This PR changes several name references to reflect that.

- Updated `package.json` and a few `README`s
- Update required node version to >= 14

### Status

One sec, gonna wipe then reinstall packages to test out Node 14.

### CODE REVIEW

**Comment by shaunanoordin** [comment]
OK, this PR is now ready 👍

**Review by srallen — CHANGES_REQUESTED** [review]
This is great! Thank you. Could you update the node version in the dockerfile to 14?

**Comment by shaunanoordin** [comment]
Good catch, thanks Sarah! I've updated the Dockerfile to use Node v14 👌

**Review by srallen — COMMENTED** [review]
LGTM. Thanks!

**Pull request merged**
